# phpMyAdmin Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: mi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: "felix"
        - name: PMA_PASSWORD
          value: "4444"
        - name: MYSQL_ROOT_PASSWORD
          value: "4444"
---
# phpMyAdmin Service
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: mi-app
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30081
  type: NodePort